### PR TITLE
Add typings for module and submodules

### PR DESCRIPTION
**Pull request by stramel**
Adds typings for the main module and submodules.

### CODE REVIEW

**Comment by stramel** [comment]
The DX of these hooks with typings feels pretty rough. Open to suggestions

**Comment by addyosmani** [comment]
Thank you for working on a PR adding typings, @stramel. I see there's already been a request for this in https://github.com/GoogleChromeLabs/react-adaptive-hooks/issues/27. I would like to keep this open to give (1) more users a chance to signal if typings are important to them and (2) more reviewers a chance to chime in on DX.

**Comment by stramel** [comment]
I think to fix the DX of using types, we always return `unsupported` as a `boolean ` instead of conditionally returning the value or unsupported. `useSaveData` already functions similarly to this.

**Comment by stramel** [comment]
Rebased and updated to match the hook definitions

**Comment by anton-karlovskiy** [comment]
@stramel cc @addyosmani 

Once we've landed https://github.com/GoogleChromeLabs/react-adaptive-hooks/pull/44, I think we can proceed with this PR.

@stramel
Could you please check my comments?

**Comment by anton-karlovskiy** [comment]
@stramel 

According to typescript [handbook](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html), they recommend `publishing to the [@types organization](https://www.npmjs.com/~types) on npm` rather than `bundling with your npm package` as long as the package is not written in Typescript.

**Comment by addyosmani** [comment]
Thank you for taking the time to work on typings support for the module and submodules, @stramel. I also appreciate the review here, @anton-karlovskiy.

My personal take is that given the package is not written in TypeScript and we have no short-mid term plans to rewrite it in TS for now, it would make more sense for typings to be published in the @types organization rather than bundling it with this package.

@stramel I think this is a reasonable compromise as it unlocks typings for users that want it. Wdyt?

**Comment by stramel** [comment]
@addyosmani I can do that

**Comment by addyosmani** [comment]
Cool. Thank you! With this in mind, I'm going to go ahead and close this PR. Let's follow up with a PR adding a link/note in the README to the typings package once it lands in the types organization? :)

**Comment by stramel** [comment]
Added a draft PR for the typings. I need to clean up the typings and add tests.

Is there anyone who would want to help maintain these types? 

@addyosmani @anton-karlovskiy

**Pull request closed without merging**
